version: "1"
services:
  - type: web
    name: PIMS
    runtime: ruby
    repo: https://github.com/mfifth/PIMS
    envVars:
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: SKIP_DB
        value: "1"
    region: oregon
    buildCommand: bundle install && rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb

  - type: worker
    name: PIMS-background-jobs
    runtime: ruby
    repo: https://github.com/mfifth/PIMS
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec good_job start